In [1]:
#importing numpy library 
import numpy as np

Creating Numpy array

In [2]:
# create numpy array using list
list = [1, 2, 3, 8]
array1 = np.array(list)

print(array1)


[1 2 3 8]


In [3]:
# create numpy array using a list
array = np.array([1, 4, 2, 9, 10])
print(array)


[ 1  4  2  9 10]


In [4]:
# create an array with 10 elements filled with zeros
array1 = np.zeros(10)
print(array1)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# create an array with 10 elements filled with ones
array1 = np.ones(10)
print(array1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
# create an array with values from 0 to 9
array1 = np.arange(10)

print("array1:", array1)

# create an array with values from 1 to 10 with a step of 2
array2 = np.arange(1, 10, 2)

print("array2:",array2)

array1: [0 1 2 3 4 5 6 7 8 9]
array2: [1 3 5 7 9]


In [7]:
# generate an array of 10 random numbers
array = np.random.rand(10)
print(array)

[0.15876353 0.19687994 0.77239508 0.72319746 0.30876164 0.41466131
 0.96611588 0.56571765 0.31436168 0.47974574]


In [9]:
# create a 2D array with 3 rows and 3 columns
array = np.array([[1, 2, 3],
                  [5, 6, 7],
                  [9, 10, 11]])

print(array)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


Data type

In [10]:
#1 int8, int16, int32, int64 - signed integer types with different bit sizes
#2 uint8, uint16, uint32, uint64 - unsigned integer types with different bit sizes
#3 float32, float64 - floating-point types with different precision levels
#4 complex64, complex128 - complex number types with different precision levels

# create an array of  integers
array1 = np.array([1 , 2 , 3 , 4])

# create an array of floating-point numbers
array2 = np.array([0.1, 0.2, 0.3 , 0.4])

# create an array of complex numbers
array3 = np.array([1+4j, 2+5j, 3+6j])

# check the data type of int_array
print("array1 dtype:" ,array1.dtype)  # prints int64

# check the data type of float_array
print("array2 dtype:" ,array2.dtype)  # prints float64

# check the data type of complex_array
print("array3 dtype:" , array3.dtype)  # prints complex128

array1 dtype: int32
array2 dtype: float64
array3 dtype: complex128


In [11]:
#Creating NumPy Arrays With a Defined Data Type

# create an array of 8-bit integers
array1 = np.array([1, 2, 3, 4], dtype='int8')

# create an array of unsigned 16-bit integers
array2 = np.array([1 ,2, 3, 4], dtype='uint16')

# create an array of 32-bit floating-point numbers
array3 = np.array([1.2, 1.3, 1.4], dtype='float32')

# create an array of 64-bit complex numbers
array4 = np.array([1+2j, 2+3j, 3+4j], dtype='complex64')

# print the arrays and their data types
print("array1", array1.dtype)
print("array2", array2.dtype)
print("array3", array3.dtype)
print("array4", array4.dtype)

array1 int8
array2 uint16
array3 float32
array4 complex64


NumPy Array Attributes


In [13]:
# create a 2-D array 
array = np.array([[2, 4, 6],
                  [1, 3, 5]])

# check the dimension of array
print("Dimension of array :" , array.ndim) 
# return total number of elements in array
print("Size of array: " ,array.size)
# return a tuple that gives size of array in each dimension
print("shape of array: " ,array.shape)
# check the data type of array
print("data type of array:" ,array.dtype)
# use of itemsize to determine size of each array element of array 
print("Item size of aaray",array.itemsize)
# print memory address of array's  data
print("Data of array is: ",array.data)

Dimension of array : 2
Size of array:  6
shape of array:  (2, 3)
data type of array: int32
Item size of aaray 4
Data of array is:  <memory at 0x0000025047393E10>


Numpy Array Indexing

In [16]:
array = np.array([1, 2, 3, 4, 5])

# access  elements using index
print(array[0])  
print(array[2])   
print(array[4]) 

#negative indexing
# access the last element
print(array[-1])   

# access the second-to-last element
print(array[-2])   

1
3
5
5
4


In [17]:
numbers = np.array([2, 5, 6, 12, 10])

# change the value of the first element
numbers[0] = 12
print("After modifying first element:",numbers)    

# change the value of the third element
numbers[2] = 14
print("After modifying third element:",numbers) 

# modify the last element
numbers[-1] = 13
print("modify the last element",numbers)   

# modify the second-to-last element
numbers[-2] = 17
print("modify the second-to-last element",numbers)  

After modifying first element: [12  5  6 12 10]
After modifying third element: [12  5 14 12 10]
modify the last element [12  5 14 12 13]
modify the second-to-last element [12  5 14 17 13]


In [18]:
#2d array indexing
# create a 2D array 
array = np.array([[1, 2, 3, 4], 
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])


# access the element at the second row and fourth column
element1 = array[1, 3] 
print("4th Element at 2nd Row:",element1)  

# access the element at the first row and second column
element2 = array[0, 1] 
print("2nd Element at First Row:",element2)  

4th Element at 2nd Row: 8
2nd Element at First Row: 2


NumPy Array Slicing

In [20]:
#syntax array[start:stop:step]

# create a 1D array 
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# slice array from index 2 to index 6 (exclusive)
print(array[2:6]) 

# slice array from index 0 to index 8 (exclusive) with a step size of 2
print(array[0:8:2])

# slice array from index 3 up to the last element
print(array[3:]) 

# items from start to end
print(array[:])  

# slice the last 3 elements of the array
# using the start parameter
print(array[-3:])   

# slice elements from 2nd-to-last to 4th-to-last element
# using the start and stop parameters
print(array[-5:-2])   

# slice every other element of the array from the end
# using the start, stop, and step parameters
print(array[-1::-2])   

[3 4 5 6]
[1 3 5 7]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[7 8 9]
[5 6 7]
[9 7 5 3 1]


In [21]:
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# generate reversed array
reversed_numbers = numbers[::-1]
print(reversed_numbers)


[12 10  8  6  4  2]


NumPy Array Reshaping

In [22]:
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8, 9])

# reshape a 1D array into a 2D array 
# with 3 rows and 3 columns
result = np.reshape(array1, (3, 3))
print(result)

[[1 3 5]
 [7 2 4]
 [6 8 9]]


In [23]:
# flatten 2D array to 1D
array1 = np.array([[1, 3], [5, 7], [9, 11]])
result = np.reshape(array1, -1)
print("Flattened 2D array:", result)

Flattened 2D array: [ 1  3  5  7  9 11]


Arithmetic Array Operations

In [24]:
#Addition

first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the + operator
result1 = first_array + second_array
print("Using the + operator:",result1) 

# using the add() function
result2 = np.add(first_array, second_array)
print("Using the add() function:",result2) 

#Subtraction

first_array = np.array([3, 9, 27, 81])
second_array = np.array([2, 4, 8, 16])

# using the - operator
result1 = first_array - second_array
print("Using the - operator:",result1) 

# using the subtract() function
result2 = np.subtract(first_array, second_array)
print("Using the subtract() function:",result2) 


#Multiplication

first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the * operator
result1 = first_array * second_array
print("Using the * operator:",result1) 

# using the multiply() function
result2 = np.multiply(first_array, second_array)
print("Using the multiply() function:",result2) 

#Division

first_array = np.array([1, 2, 3])
second_array = np.array([4, 5, 6])

# using the / operator
result1 = first_array / second_array
print("Using the / operator:",result1) 

# using the divide() function
result2 = np.divide(first_array, second_array)
print("Using the divide() function:",result2) 

#Exponentiation

array1 = np.array([1, 2, 3])

# using the ** operator
result1 = array1 ** 2
print("Using the ** operator:",result1) 

# using the power() function
result2 = np.power(array1, 2)
print("Using the power() function:",result2) 

#modulus

first_array = np.array([9, 10, 20])
second_array = np.array([2, 5, 7])

# using the % operator
result1 = first_array % second_array
print("Using the % operator:",result1) 

# using the mod() function
result2 = np.mod(first_array, second_array)
print("Using the mod() function:",result2)

Using the + operator: [ 3  7 11 15]
Using the add() function: [ 3  7 11 15]
Using the - operator: [ 1  5 19 65]
Using the subtract() function: [ 1  5 19 65]
Using the * operator: [ 2 12 30 56]
Using the multiply() function: [ 2 12 30 56]
Using the / operator: [0.25 0.4  0.5 ]
Using the divide() function: [0.25 0.4  0.5 ]
Using the ** operator: [1 4 9]
Using the power() function: [1 4 9]
Using the % operator: [1 0 6]
Using the mod() function: [1 0 6]


NumPy Array Statistical Functions

In [25]:
marks = np.array([76, 78, 80, 65, 86])

# compute the mean of marks
mean = np.mean(marks)
print("Mean:",mean)

# compute the median of marks
median = np.median(marks)
print("Median:",median)

# find the minimum and maximum marks
min = np.min(marks)
print("Minimum marks:", min)

max = np.max(marks)
print("Maximum marks:", max)

Mean: 77.0
Median: 78.0
Minimum marks: 65
Maximum marks: 86


NumPy Comparison Operators

In [26]:
array1 = np.array([1, 2, 3 , 4])
array2 = np.array([4 , 3, 2, 1])

# less than operator
result1 = array1 < array2
print("array1 < array2:",result1)   

# greater than operator
result2 = array1 > array2
print("array1 > array2:",result2)
  
# equal to operator
result3 = array1 == array2
print("array1 == array2:",result3)    

array1 < array2: [ True  True False False]
array1 > array2: [False False  True  True]
array1 == array2: [False False False False]


NumPy Comparison Functions

In [27]:
array1 = np.array([9, 12, 21])
array2 = np.array([21, 12, 9])

# use of less()
result = np.less(array1, array2)
print("Using less():",result)    

# use of less_equal()
result = np.less_equal(array1, array2)
print("Using less_equal():",result)    

# use of greater()
result = np.greater(array1, array2)
print("Using greater():",result)   

# use of greater_equal()
result = np.greater_equal(array1, array2)
print("Using greater_equal():",result)   

# use of equal()
result = np.equal(array1, array2)
print("Using equal():",result)  

# use of not_equal()
result = np.not_equal(array1, array2)
print("Using not_equal():",result)  

Using less(): [ True False False]
Using less_equal(): [ True  True False]
Using greater(): [False False  True]
Using greater_equal(): [False  True  True]
Using equal(): [False  True False]
Using not_equal(): [ True False  True]


NumPy Logical Operations

In [28]:
x1 = np.array([True, False, True])
x2 = np.array([False, False, True])

# Logical AND
print(np.logical_and(x1, x2))

# Logical OR
print(np.logical_or(x1, x2))

# Logical NOT
print(np.logical_not(x1))

[False False  True]
[ True False  True]
[False  True False]


NumPy String Functions


In [30]:
#element wise concat
array1 = np.array(['Shailendra: ', 'id: '])
array2 = np.array(['15', 'xxxxx'])

# perform element-wise array string concatenation
result = np.char.add(array1, array2)

print(result)

['Shailendra: 15' 'id: xxxxx']


In [31]:
#multiplication
# define array with three string elements
array1 = np.array(['A', 'B', 'C']) 

#  repeat each element in array1 three times 
result = np.char.multiply(array1, 3)  

print(result)  


['AAA' 'BBB' 'CCC']


In [33]:
# capitalize
# define an array with three string elements
array1 = np.array(['shailendra', 'rahul', 'rishi'])  

# capitalize the first letter of each string in array1 
result = np.char.capitalize(array1)  

print(result) 

# convert all string elements to uppercase
result1 = np.char.upper(array1)

# convert all string elements to lowercase
result2 = np.char.lower(array1)

print("To Uppercase: ",result1)
print("To Lowercase: ",result2)

# join the strings in the array using a dash as the delimiter
result = np.char.join('-', array1)

print(result)


['Shailendra' 'Rahul' 'Rishi']
To Uppercase:  ['SHAILENDRA' 'RAHUL' 'RISHI']
To Lowercase:  ['shailendra' 'rahul' 'rishi']
['s-h-a-i-l-e-n-d-r-a' 'r-a-h-u-l' 'r-i-s-h-i']


In [34]:
#Equal or not

# create two arrays of strings
array1 = np.array(['Java', 'Python', 'Swift'])
array2 = np.array(['C++', 'Python', 'R'])

# check if each element of the arrays is equal
result = np.char.equal(array1, array2)

print(result)


[False  True False]


This document contain all the basic numpy commands 
That's all from my side